mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from polls import views


handler404 = views.error_404

urlpatterns = [
    path('', RedirectView.as_view(url='polls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', views.signup, name='signup'),
    path('polls/', include('polls.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

polls/models.py
import datetime
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class Question(models.Model):
    """Question model with publish date and end date(optional)"""
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published', default=timezone.localtime, blank=True)
    end_date = models.DateTimeField('date ended', null=True, blank=True)

    def __str__(self):
        """Return question text description string of each question."""
        return self.question_text

    def was_published_recently(self):
        """Return if the question is published recently(1 day)"""
        now = timezone.localtime()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def is_published(self):
        """Return if the question is published or not."""
        now = timezone.localtime()
        return self.pub_date <= now

    def can_vote(self):
        """Return if voting is allowed or not."""
        now = timezone.localtime()
        if self.end_date is None:
            return self.pub_date <= now
        return self.pub_date <= now <= self.end_date


class Choice(models.Model):
    """Choice model for each question"""
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)

    # votes = models.IntegerField(default=0)

    @property
    def votes(self):
        """Count all the votes for this choice"""
        return self.vote_set.count()

    def __str__(self):
        """Return choice text description string of each choice."""
        return self.choice_text


class Vote(models.Model):
    """Record a choice for a question made by a user."""
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.user.username} vote for {self.choice.choice_text} in {self.choice.question.question_text}"

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from .models import Choice, Question, Vote


def error_404(request, exception):
    return render(request, 'polls/index.html')


def signup(request):
    """Register a new user."""
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if not form.is_valid():
            messages.error(request, 'The form is invalid, your username or password may not be with the rules')
            return redirect('signup')
        if form.is_valid():
            form.save()
            # get named fields from the form data
            username = form.cleaned_data.get('username')
            # password input field is named 'password1'
            raw_passwd = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_passwd)
            login(request, user)
        return redirect('polls:index')
    else:
        # create a user form and display it the signup page
        form = UserCreationForm()
    return render(request, 'registration/signup.html', {'form': form})


class IndexView(generic.ListView):
    """Index view page of this application."""
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.localtime()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    """Detail view page of this application."""
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.localtime())

    def get(self, request, *args, **kwargs):
        """Redirect user to responding pages depend on that poll's status when viewing poll's details"""
        try:
            question = get_object_or_404(Question, pk=kwargs["pk"])
        except (KeyError, Question.DoesNotExist):
            messages.error(request, 'Requested poll does not exist')
            return HttpResponseRedirect(reverse('polls:index'))
        if not question.can_vote():
            messages.error(request, 'You cannot vote on unpublished or ended poll')
            return HttpResponseRedirect(reverse('polls:index'))
        this_user = request.user
        if not this_user.is_authenticated:
            return redirect('login')
        try:
            past_vote = Vote.objects.get(user=this_user, choice__question=question)
            selected_choice = past_vote.choice
        except Vote.DoesNotExist:
            selected_choice = ''
        return render(request, 'polls/detail.html', {
            'question': question,
            'selected_choice': selected_choice})


class ResultsView(generic.DetailView):
    """Results view page of this application."""
    model = Question
    template_name = 'polls/results.html'

    def get_queryset(self):
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.localtime()).order_by('-pub_date')[:5]

    def get(self, request, *args, **kwargs):
        """Redirect user to responding pages depend on that poll's status when viewing poll's results"""
        try:
            question = get_object_or_404(Question, pk=kwargs["pk"])
        except (KeyError, Question.DoesNotExist):
            messages.error(request, 'Requested poll does not exist')
            return HttpResponseRedirect(reverse('polls:index'))
        if not question.is_published():
            messages.error(request, 'This poll is not published yet')
            return HttpResponseRedirect(reverse('polls:index'))
        return render(request, 'polls/results.html', {'question': question})


@login_required
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if not question.can_vote():
        messages.error(request, "This question is not available for voting.")
        return HttpResponseRedirect(reverse('polls:index'))
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        messages.error(request, "You didn't select a choice.")
        return render(request, 'polls/detail.html', {'question': question, })
    this_user = request.user
    try:
        current_vote = Vote.objects.get(user=this_user, choice__question=question)
        current_vote.choice = selected_choice
    except Vote.DoesNotExist:
        current_vote = Vote(user=this_user, choice=selected_choice)
    current_vote.save()
    messages.success(request, "Your vote has been recorded")
    return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

polls/templates/polls/detail.html
{% load static %}

<html lang="en">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">

    <body>
    {% if user.is_authenticated %}
        <p>You are currently logging in as {{ user.username }}, <a href="{% url 'logout' %}">Logout</a></p>
    {% else %}
        Please <a href="{% url 'login' %}">Login</a> before being able to vote
    {% endif %}
        <form action="{% url 'polls:vote' question.id %}" method="post">
            {% csrf_token %}
            <fieldset>
                <legend><h1>{{question}}</h1></legend>
                {% if messages %}
                    {% for message in messages %}
                        <p style="color: orangered;"><strong>{{ message }}</strong></p>
                    {% endfor %}
                {% endif %}
                {% for choice in question.choice_set.all %}
                {% if choice == selected_choice %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" checked>
                {% else %}
                    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
                {% endif %}
                    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
            </fieldset>
            <button type="submit">Vote</button>
        </form>
        <a href="{% url 'polls:index' %}"><button>Back to List of Polls</button></a>
        <a href="{% url 'polls:results' question.id %}"><button>See Result</button></a>
    </body>
</html>

polls/templates/polls/index.html
{% load static %}

<html lang="en">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">

    <body>
        {% if messages %}
            {% for message in messages %}
                <div role="alert" style="color: orangered;">
                    {{ message }}
                </div>
            {% endfor %}
        {% endif %}
        {% if user.is_authenticated %}
            <p>You are currently logging in as {{ user.username }}, <a href="{% url 'logout' %}">Logout</a></p>
        {% else %}
            Please <a href="{% url 'login' %}">Login</a> before being able to vote
        {% endif %}
        <h1>List of KU-Polls Questions</h1>
        {% if latest_question_list %}
            <table>
            <tr>
                <th>Questions List</th>
                <th>Results</th>
                <th>Publish date</th>
                <th>End date</th>
            </tr>
                {% for question in latest_question_list %}
            <tr>
                <td>{{ forloop.counter }}. <a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></td>
                <td><a href="{% url 'polls:results' question.id %}"><button>See Result</button></a></td>
                <td>{{ question.pub_date }}</td>
                <td>{{ question.end_date }}</td>
            </tr>
                {% endfor %}
            </table>
        {% else %}
            <p>No available polls.</p>
        {% endif %}
    </body>
</html>

polls/templates/polls/results.html
{% load static %}

<html lang="en">
    <link rel="stylesheet" href="{% static 'polls/style.css' %}">

    <body>
        {% if user.is_authenticated %}
            <p>You are currently logging in as {{ user.username }}, <a href="{% url 'logout' %}">Logout</a></p>
        {% else %}
            Please <a href="{% url 'login' %}">Login</a> before being able to vote
        {% endif %}
        {% if messages %}
            {% for message in messages %}
                <p style="color: orangered;"><strong>{{ message }}</strong></p>
            {% endfor %}
        {% endif %}
        <h1>{{ question.question_text }}</h1>
        <h2>Voting Results</h2>
        <ul>
            {% for choice in question.choice_set.all %}
                <li>{{ choice.choice_text }}: {{ choice.votes }}</li>
            {% endfor %}
        </ul>

        <a href="{% url 'polls:index' %}"><button>Back to polls list</button></a>
    </body>
</html>